import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const fontPoppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "600", "800"]
});


export const metadata: Metadata = {
  title: "Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.className} antialiased`}
        suppressHydrationWarning={true}
        id="root"
      >
        <main className="container mx-auto bg-background min-h-screen text-white">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
